In [1]:
import pandas as pd
array_ = []
with open("tmp_file.txt") as file:
    for line in file:
        array_.append([int(i) for i in line.rstrip().split()])

In [2]:
b = array_

In [3]:
print(len(b))#53845

53845

In [4]:
###OR_suit1 must have 135 122 92 113
suitable_or1 = []
count = 0
for element in b:
    #count +=1
    #print(count)
    if 135 in element and 92 in element and 113 in element and 122 in element:
        suitable_or1.append(element)

In [5]:
print(len(suitable_or1))

335

In [6]:
def check(b,my_list_):
    for element in b:
        if(element not in my_list_):#yes
            return False#false
        else:
            my_list_.remove(element)
    return my_list_
def double_check(array_equal):
    print(array_equal)
    ts3 = [*array_equal[0], *array_equal[1],*array_equal[2]]
    my_list_1 = [59, 31, 39, 30, 35, 108, 113, 135, 44, 48, 124, 55, 30, 48, 74, 71, 113, 74, 74, 26, 26, 122, 92, 113, 43, 23, 43, 74, 74, 39, 39, 39, 39, 113, 31]
    print(sorted(my_list_1)==sorted(ts3))
    print(sum(array_equal[0])==sum(array_equal[1])==sum(array_equal[2]))

In [21]:
global_yes = []
count = 0
len_b = len(b)
len_suitable_or1 = len(suitable_or1)
for b1 in range(len_b):
     for b0 in range(b1,len_suitable_or1):
      count += 1
      my_list = [59, 31, 39, 30, 35, 108, 113, 135, 44, 48, 124, 55, 30, 48, 74, 71, 113, 74, 74, 26, 26, 122, 92, 113, 43, 23, 43, 74, 74, 39, 39, 39, 39, 113, 31]
      for element in suitable_or1[b0]:
        my_list.remove(element)
      a = check(b[b1],my_list)
      if(a != False):
        print(count)

        global_yes.append(([ b[b1], suitable_or1[b0], a]))

5575
5594
5609
5611
5647
5648
5652
5654
5659
5662
5663
5665
5668
5672
5678
5679
5680
5683
5684
5685
5687
5688
5689
5692
5697
5698
5699
5702
5752
5754
5755
5756
5757
5758
5759
5760
5763
5764
5765
5766
5767
5769
5770
5771
5772
5773
5774
5775
5777
5778
5780
5781
5782
5783
5784
5785
5786
5787
5788
5789
5791
5793
5794
5795
5796
5797
5798
5799
5800
5801
5802
5803
5804
5805
5806
5809
5810
5811
5812
5813
5814
5815
5816
5817
5818
5819
5820
5821
5822
5823
5826
5841
5842
5843
5844
5845
5846
5847
5848
5849
5850
5851
5852
5853
5854
5855
5856
5857
5858
5859
5860
5861
5862
5863
5864
5866
5867
5868
5871
5873
5875
5877
9332
9351
9353
9357
9358
9359
9361
9363
9365
9367
9368
9369
9371
9372
9373
9375
9376
9378
9379
9386
9389
9401
9416
9417
9422
9425
9426
9430
9436
9437
9439
9442
9443
9444
9445
9446
9447
9448
9449
9451
9452
9453
9455
9457
9458
9459
9460
9461
9464
9466
9468
9469
9470
9471
9472
9473
9474
9475
9476
9477
9478
9479
9480
9481
9482
9483
9484
9485
9487
9488
9489
9491
9493
9495
9496
9499
9502
9506
9509
9511
9514
9518
9521
9524
9532
9534
9535
9537
9538
9539
9541
9543
9545
9546
9547
9549
9551
9553
9554
9556
9557
9561
9563
9565
9566
9569
9570
9573
9574
9575
9576
9577
9578
9580
9581
9584
9586
9588
9592
9596
9600
9606
9607
9608
9609
9610
9611
9612
9614
32212
32215
32217
32221
32229
32234
32327
32330
32334
32336
32338
32339
32342
32344
32346
32349
32352
32353
32354
32356
32358
32401
32402
32405
32406
32407
32629
32630
32646
32647
32650
32655
32656
32665
32666
32724
32725
32726
32731
32732
32740
32741
32751
32752
32753
32754
32763
32764
32765
32766
32767
32769
32770
32771
32772
32773
32778
32779
32783
32784
32787
32788
32790
32809
32811
32813
32815
32816
32817
32821
32825
32831
32835
32842
36580
36584
36585
36587
36588
36589
36592
36597
36599
36601
36602
36652
36653
36654
36655
36656
36658
36659
36660
36661
36662
36663
36664
36665
36666
36667
36668
36669
36670
36671
36672
36673
36674
36675
36676
36678
36679
36683
36685
36688
36689
36691
36692
36693
36694
36695
36697
36698
36699
36701
36703
36704
36708
36709
36710
36712
36713
36714
36716
36717
36721
36722
36724
36725
36743
36745
36748
36749
36750
36751
36752
36753
36755
36756
36759
36760
36763
36765
36772
36774
36777
38895
38896
38897
38900
38952
38953
38954
38955
38962
38963
38964
38965
38967
38968
38969
38970
38975
38976
38978
38979
38980
38981
38982
38989
38991
38998
38999
39000
39001
39002
39003
39004
39011
39012
39013
39014
39015
39020
39021
39024
39043
39044
39045
39046
39047
39052
39053
39054
39055
39059
39060
39061
39062
39064
39069
39071
40930
40932
40937
40941
40943
40945
40948
40952
40953
40955
40960
40965
40967
40985
41047
41048
41051
41052
41104
41106
41107
41108
41109
41110
41111
41112
41115
41116
41117
41118
41119
41121
41122
41123
41124
41125
41126
41127
41129
41130
41132
41133
41134
41135
41136
41137
41138
41139
41140
41141
41142
41143
41145
41146
41147
41148
41149
41150
41151
41152
41153
41154
41155
41156
41157
41158
41161
41162
41164
41165
41166
41167
41168
41169
41170
41171
41172
41173
41174
41175
41178
41193
41194
41195
41196
41197
41198
41199
41200
41201
41202
41203
41204
41205
41206
41207
41208
41209
41210
41211
41212
41213
41214
41215
41216
41218
41219
41220
41223
41225
41227
41229
41449
41450
41451
41452
41453
41454
41455
41456
41457
41458
41459
41461
41462
41463
41464
41465
41466
41467
41470
41471
41472
41473
41474
41475
41476
41477
41478
41479
41480
41481
41482
41483
41484
41485
41486
41488
41489
41490
41491
41492
41493
41495
41496
41497
41498
41499
41502
41503
41504
41505
41506
41507
41511
41512
41515
41516
41517
41518
41519
41520
41521
41522
41523
41538
41539
41540
41541
41542
41543
41544
41546
41547
41548
41550
41551
41552
41554
41555
41556
41557
41558
41559
41560
41561
41562
41563
41564
41565
41566
41567
41568
41569
41572
41573
41574
46285
46288
46289
46293
46296
46302
46303
46304
46305
46314
46315
46316
46319
46320
46321
46322
46324
46326
46330
46331
46332
46338
46339
46342
46343
46344
46345
46348
46349
46350
46352
46354
46359
46374
46376
46381
46382
46385
46386
46390
46393
46400
46708
46714
46716
46719
46723
46731
46736
46738
46740
46743
46791
46795
46800
46801
46802
46803
46804
46805
46806
46807
46808
46809
46813
46817
46824
46827
52627
52628
52630
52631
52633
52634
52635
52636
52637
52642
52643
52644
52645
52646
52647
52649
52650
52651
52655
52675
52677
52678
52680
52683
52684
52685
52688
52689
52692
52699
52704
52706
52711
52716
52720
52724
52725
52728
52730
52740
52759
52760
52764
52765
52768
52770
52773
52779
52780
52782
52785
52786
52788
52789
52790
52791
52793
52794
55071
55076
55078
55080
55083
55087
55090
55093
55096
55100
55101
55102
55104
55721
55723
55729
55737
55745
55746
55747
55748
55749
55981
55985
55989
55995
55996
55997
55998
55999
56000
56001
56003

In [22]:
print(len(global_yes))#829
###let the outpatient goes later.

828

In [23]:
import csv

data = global_yes

with open('global_yes1.txt', 'w') as f:
    csv.writer(f, delimiter=' ').writerows(data)

In [24]:
new_global_yes_ = []
for idx in range(len(global_yes)):
    if 59 in global_yes[idx][1] and 31 in global_yes[idx][1] or 59 in global_yes[idx][0] and 31 in global_yes[idx][0] or 59 in global_yes[idx][2] and 31 in global_yes[idx][2]:
        new_global_yes_.append(global_yes[idx])
print(len(new_global_yes_))

153

In [25]:
new_global_yes_2 = []
for idx in range(len(new_global_yes_)):
    if 39 in new_global_yes_[idx][1] and 30 in new_global_yes_[idx][1] or 39 in new_global_yes_[idx][0] and 30 in new_global_yes_[idx][0] or 39 in new_global_yes_[idx][2] and 30 in new_global_yes_[idx][2]:
        new_global_yes_2.append(new_global_yes_[idx])
print(len(new_global_yes_2))

133

In [26]:
new_global_yes_3 = []
for idx in range(len(new_global_yes_2)):
    if 108 in new_global_yes_2[idx][1] and 113 in new_global_yes_2[idx][1] or 108 in new_global_yes_2[idx][0] and 113 in new_global_yes_2[idx][0] or 108 in new_global_yes_2[idx][2] and 113 in new_global_yes_2[idx][2]:
        new_global_yes_3.append(new_global_yes_2[idx])
print(len(new_global_yes_3))

133

In [27]:
new_array = []
for idx in range(len(new_global_yes_3)):
    if 135 in new_global_yes_3[idx][1] and 59 in new_global_yes_3[idx][2] and 31 in new_global_yes_3[idx][2] and 39 in new_global_yes_3[idx][2] and 30 in new_global_yes_3[idx][2] and 108 in new_global_yes_3[idx][0] and 113 in new_global_yes_3[idx][0]:
        new_array.append(new_global_yes_3[idx])
print(len(new_array))

28

In [28]:
new_array2 = []
for idx in range(len(new_array)):
    if 35 in new_array[idx][1]:
        new_array2.append(new_array[idx])
new_array3 = []
for idx in range(len(new_array)):
    if 35 in new_array[idx][0]:
        new_array3.append(new_array[idx])
print(len(new_array2))
print(len(new_array3))
print(sum(new_array2[0][1]))

8
2
747

In [29]:
from itertools import combinations
def sub_set_sum(my_array, sub_set_sum):
   sub_array=[]
   for i in range(len(my_array)):
      for my_sub_set in combinations(my_array, i):

         if sum(my_sub_set) == sub_set_sum:
            a = list(my_sub_set)
            a.sort()
            if a not in sub_array:
                sub_array.append(a)
                print(a)
            
   return sub_array

In [30]:
print(new_array3[0])
print(new_array3[1])

[[31, 35, 39, 71, 108, 113, 113, 113, 124], [23, 26, 26, 30, 39, 43, 43, 55, 92, 113, 122, 135], [59, 44, 48, 30, 48, 74, 74, 74, 74, 74, 39, 39, 39, 31]]
[[31, 35, 39, 71, 108, 113, 113, 113, 124], [26, 26, 30, 39, 39, 39, 43, 43, 92, 113, 122, 135], [59, 44, 48, 55, 30, 48, 74, 74, 74, 23, 74, 74, 39, 31]]

In [31]:
global_yes = new_array2

In [32]:

for idx in range(len(global_yes)):
        if 135 in global_yes[idx][1]:
            global_yes[idx][1].remove(135)
        if 122 in global_yes[idx][1]:
            global_yes[idx][1].remove(122)
        if 92 in global_yes[idx][1]:
            global_yes[idx][1].remove(92)
        if 113 in global_yes[idx][1]:
            global_yes[idx][1].remove(113)
        if 59 in global_yes[idx][2]:
            global_yes[idx][2].remove(59)
        if 31 in global_yes[idx][2]:
            global_yes[idx][2].remove(31)
        if 39 in global_yes[idx][2]:
            global_yes[idx][2].remove(39)
        if 30 in global_yes[idx][2]:
            global_yes[idx][2].remove(30)
        if 108 in global_yes[idx][0]:
            global_yes[idx][0].remove(108)
        if 113 in global_yes[idx][0]:
            global_yes[idx][0].remove(113)
        if 35 in global_yes[idx][1]:
            global_yes[idx][1].remove(35)
print(sum(global_yes[0][1]))
print(sum(global_yes[0][2]))
print(sum(global_yes[0][0]))

250
588
300

In [33]:
# Import pandas
import pandas as pd
import numpy as np

# Load the xlsx file
excel_data = pd.read_excel('Surgical_Cases_Master.xlsx')
# Read the values of the file in the dataframe
data = pd.DataFrame(excel_data)


excel_data_temp = data
##or1
count = 11
for idx3 in range(len(global_yes)):
 for idx2 in range(len(global_yes[idx3][1])):
    for idx in range(len(excel_data_temp.index)):
        if((excel_data_temp.iloc[idx].Expected_Surgical_Time == global_yes[idx3][1][idx2]
           and pd.isnull(excel_data_temp.iloc[idx].OR_Suite))):
            excel_data_temp.at[idx,'OR_Suite']='OR1'
            count +=1
            excel_data_temp.at[idx,'Case_Scheduling_Order']= count
            break
##or2
 for idx2 in range(len(global_yes[idx3][0])):
    for idx in range(len(excel_data_temp.index)):
        if((excel_data_temp.iloc[idx].Expected_Surgical_Time == global_yes[idx3][0][idx2]
           and pd.isnull(excel_data_temp.iloc[idx].OR_Suite))):
            excel_data_temp.at[idx,'OR_Suite']='OR3'
            count +=1
            excel_data_temp.at[idx,'Case_Scheduling_Order']= count
            break

 for idx2 in range(len(global_yes[idx3][2])):
    for idx in range(len(excel_data_temp.index)):
        if((excel_data_temp.iloc[idx].Expected_Surgical_Time == global_yes[idx3][2][idx2]
           and pd.isnull(excel_data_temp.iloc[idx].OR_Suite))):
            excel_data_temp.at[idx,'OR_Suite']='OR2'
            count +=1
            excel_data_temp.at[idx,'Case_Scheduling_Order']= count
            break
 excel_data_temp.to_excel("output"+str(idx3)+".xlsx",sheet_name='AllCases')

ValueError: could not convert string to float: 'OR1'

In [43]:
# Import pandas
import pandas as pd
import numpy as np

# Load the xlsx file
excel_data = pd.read_excel('Surgical_Cases_Master.xlsx')
# Read the values of the file in the dataframe
data = pd.DataFrame(excel_data)


excel_data_temp = data
print(excel_data_temp)
array_or1=[26,27,25,33,29,8]
array_or2=[1,2,35,9,12,11,10,4,35]
array_or3=[15,12,28,11,20,14,2,14]
count = 0
for idx2 in range(len(array_or1)):
    for idx in range(len(excel_data_temp.index)):
        if((excel_data_temp.iloc[idx].Case_Num  == array_or1[idx2]
           and pd.isnull(excel_data_temp.iloc[idx].OR_Suite))):
            excel_data_temp.at[idx,'OR_Suite']="OR1"
            count +=1
            excel_data_temp.at[idx,'Case_Scheduling_Order']= count
            break
for idx2 in range(len(array_or2)):
    for idx in range(len(excel_data_temp.index)):
        if((excel_data_temp.iloc[idx].Case_Num  == array_or2[idx2]
           and pd.isnull(excel_data_temp.iloc[idx].OR_Suite))):
            excel_data_temp.at[idx,'OR_Suite']="OR2"
            count +=1
            excel_data_temp.at[idx,'Case_Scheduling_Order']= count
            break
for idx2 in range(len(array_or3)):
    for idx in range(len(excel_data_temp.index)):
        if((excel_data_temp.iloc[idx].Case_Num  == array_or3[idx2]
           and pd.isnull(excel_data_temp.iloc[idx].OR_Suite))):
            excel_data_temp.at[idx,'OR_Suite']="OR3"
            count +=1
            excel_data_temp.at[idx,'Case_Scheduling_Order']= count
            break
print(excel_data_temp)
excel_data_temp.to_excel("output"+".xlsx",sheet_name='AllCases')

    Row#  Case_Num Case_Type Block_Group Patient_Type Service Procedure  \
0    NaN        23     Addon         GRM    Inpatient   OBGyn    OBGyn3
1    NaN        24     Addon         GRM    Inpatient   OBGyn    OBGyn4
2    NaN        22     Addon         GRM    Inpatient   OBGyn    OBGyn2
3    NaN         8     Block         GRM    Inpatient   OBGyn    OBGyn1
4    1.0         1     Block         XYZ    Inpatient   Ortho    Ortho1
5    2.0         2     Block         XYZ    Inpatient   Ortho    Ortho2
6    3.0         3     Block         ABC   Outpatient    Opth     Opth1
7    4.0         4     Block         ABC   Outpatient    Opth     Opth2
8    5.0         5     Block         RST    Inpatient    Vasc     Vasc1
9    6.0         6     Block         CCR    Inpatient   Ortho    Ortho6
10   7.0         7     Block         CCR    Inpatient   Ortho    Ortho7
11   NaN         9     Addon         XYZ    Inpatient   Ortho    Ortho3
12   NaN        10     Addon         XYZ    Inpatient   Ortho    Ortho4
13   NaN        11     Addon         XYZ    Inpatient   Ortho    Ortho5
14   NaN        12     Addon         XYZ    Inpatient   Ortho    Ortho9
15   NaN        13     Addon         ABC   Outpatient    Opth     Opth2
16   NaN        14     Addon         RST    Inpatient    Vasc     Vasc2
17   NaN        15     Addon         RST    Inpatient    Vasc     Vasc3
18   NaN        16     Addon         RMT    Inpatient     Gen      Gen1
19   NaN        17     Addon         MTC    Inpatient     Gen      Gen2
20   NaN        18     Addon         MTC    Inpatient     Gen      Gen3
21   NaN        19     Addon         MTC    Inpatient     Gen      Gen4
22   NaN        20     Addon         CCR    Inpatient   Ortho    Ortho8
23   NaN        21     Addon         CCR    Inpatient   Ortho    Ortho8
24   NaN        25     Addon         RRR    Inpatient     Gen      Gen5
25   NaN        26     Addon         SSS    Inpatient     Gen      Gen6
26   NaN        27     Addon         SSS    Inpatient     Gen      Gen7
27   NaN        28     Addon         TTT    Inpatient    Vasc     Vasc3
28   NaN        29     Addon         TTT    Inpatient    Vasc     Vasc3
29   NaN        30     Addon         UUU   Outpatient   Optho    Optho4
30   NaN        31     Addon         UUU   Outpatient   Optho    Optho4
31   NaN        32     Addon         UUU   Outpatient   Optho    Optho4
32   NaN        33     Addon         UUU   Outpatient   Optho    Optho4
33   NaN        34     Addon         VVV    Inpatient   Ortho    Ortho9
34   NaN        35     Addon         VVV    Inpatient   Ortho    Ortho2

           Surgeon OR_Suite  Allotted_PreOp_Time Wheels_In_to_Incision_Time  \
0         Dr Grace      NaN                   20               normal(19,2)
1         Dr Grace      NaN                   20               normal(23,3)
2         Dr Grace      OR1                   20               normal(25,3)
3         Dr Grace      NaN                   20               normal(28,3)
4         Dr Smith      NaN                   20               normal(11,2)
5         Dr Smith      NaN                   20                normal(5,1)
6         Dr Brown      NaN                   20                normal(8,1)
7         Dr Brown      NaN                   20               normal(10,1)
8         Dr Jones      NaN                   20                normal(8,1)
9          Dr Mack      NaN                   20               normal(20,2)
10         Dr Mack      NaN                   20               normal(23,3)
11        Dr Smith      NaN                   20                normal(9,1)
12        Dr Smith      NaN                   20               normal(10,1)
13        Dr Smith      NaN                   20               normal(15,6)
14        Dr Smith      NaN                   20               normal(13,1)
15        Dr Brown      NaN                   20               normal(10,1)
16        Dr Jones      NaN                   20               normal(10,1)
17        Dr Jones      NaN                   20               normal(15,2)
18     Dr Brittany      NaN                   20               normal(12,2)
19     Dr Brittany      NaN                   20               normal(23,3)
20     Dr Brittany      NaN                   20               normal(15,2)
21     Dr Brittany      NaN                   20               normal(15,2)
22         Dr Mack      NaN                   20                normal(5,1)
23         Dr Mack      NaN                   20                normal(5,1)
24    Gen Surgeons      NaN                   20                normal(8,1)
25    Gen Surgeons      NaN                   20                normal(5,1)
26    Gen Surgeons      NaN                   20                normal(5,1)
27   Vasc Surgeons      NaN                   20               normal(15,2)
28   Vasc Surgeons      NaN                   20               normal(15,2)
29  Optho Surgeons      NaN                   20                normal(8,1)
30  Optho Surgeons      NaN                   20                normal(8,1)
31  Optho Surgeons      NaN                   20                normal(8,1)
32  Optho Surgeons      NaN                   20                normal(8,1)
33  Ortho Surgeons      NaN                   20               normal(23,3)
34        Dr Smith      NaN                   20                normal(5,1)

   Incision_to_Closure_Time Closure_to_Wheels_Out_Time  \
0              normal(38,4)               normal(19,2)
1              normal(45,5)               normal(23,3)
2              normal(50,5)               normal(25,3)
3              normal(55,6)               normal(28,3)
4              normal(23,3)               normal(11,2)
5              normal(12,2)                normal(6,1)
6              normal(15,2)                normal(8,1)
7               normal(7,2)                normal(5,1)
8              normal(15,2)                normal(4,1)
9              normal(50,5)               normal(20,2)
10             normal(45,5)               normal(23,3)
11             normal(18,2)                normal(9,1)
12             normal(20,2)               normal(10,1)
13            normal(70,15)               normal(15,5)
14             normal(18,2)               normal(12,3)
15              normal(7,2)                normal(5,1)
16             normal(20,2)               normal(10,1)
17             normal(30,3)               normal(15,2)
18             normal(31,4)               normal(12,2)
19             normal(45,5)               normal(23,3)
20             normal(30,3)               normal(15,2)
21             normal(30,3)               normal(15,2)
22             normal(10,1)                normal(5,1)
23             normal(10,1)                normal(5,1)
24             normal(19,2)                normal(8,1)
25              normal(7,1)                normal(5,1)
26             normal(23,3)                normal(5,1)
27             normal(30,3)               normal(15,2)
28             normal(30,3)               normal(15,2)
29             normal(15,2)                normal(8,1)
30             normal(15,2)                normal(8,1)
31             normal(15,2)                normal(8,1)
32             normal(15,2)                normal(8,1)
33             normal(45,5)               normal(23,3)
34             normal(12,2)                normal(6,1)

   Room_Clean_and_Prep_Time  Expected_Surgical_Time  Expected_Turnover_Time  \
0              normal(27,3)                      92                      33
1              normal(20,2)                     113                      24
2              normal(35,4)                     122                      43
3              normal(57,6)                     135                      69
4              normal(25,3)                      59                      31
5              normal(13,1)                      31                      15
6              normal(16,2)                      39                      20
7              normal(13,1)                      30                      15
8              normal(15,2)                      35                      19
9              normal(28,3)                     108                      34
10             normal(37,4)                     113                      45
11             normal(18,2)                      44                      22
12             normal(20,2)                      48                      24
13             normal(52,5)                     124                      62
14             normal(23,2)                      55                      27
15             normal(13,1)                      30                      15
16             normal(20,2)                      48                      24
17             normal(31,3)                      74                      37
18             normal(30,3)                      71                      36
19             normal(34,3)                     113                      40
20             normal(26,3)                      74                      32
21             normal(31,3)                      74                      37
22             normal(11,1)                      26                      13
23             normal(17,2)                      26                      21
24             normal(18,2)                      43                      22
25             normal(10,1)                      23                      12
26             normal(18,2)                      43                      22
27             normal(22,2)                      74                      26
28             normal(31,3)                      74                      37
29             normal(16,2)                      39                      20
30             normal(24,2)                      39                      28
31             normal(18,2)                      39                      22
32             normal(19,2)                      39                      23
33             normal(36,4)                     113                      44
34             normal(13,1)                      31                      15

   PACU_Recovery_Time  Expected_Earnings  Case_Scheduling_Order  \
0       normal(120,2)               2675                    NaN
1       normal(120,2)               1760                    NaN
2       normal(180,2)               1883                    NaN
3       normal(180,2)               1020                    NaN
4       normal(100,1)               1321                    NaN
5       normal(120,2)               3116                    NaN
6       normal(120,2)               1994                    NaN
7       normal(120,2)               4005                    NaN
8       normal(110,2)               3054                    NaN
9       normal(100,1)               2443                    NaN
10      normal(120,2)               4134                    NaN
11      normal(110,2)               4423                    NaN
12      normal(110,2)               2516                    NaN
13      normal(120,2)               6675                    NaN
14      normal(110,2)               5122                    NaN
15      normal(120,2)               1829                    NaN
16      normal(110,2)               2887                    NaN
17      normal(100,1)               4876                    NaN
18      normal(120,2)               1721                    NaN
19      normal(120,2)               1882                    NaN
20      normal(110,2)               1533                    NaN
21      normal(110,2)               2122                    NaN
22       normal(90,9)               6122                    NaN
23       normal(90,9)               2010                    NaN
24       normal(90,9)               3669                    NaN
25       normal(90,9)               4435                    NaN
26       normal(90,9)               6327                    NaN
27       normal(90,9)               4371                    NaN
28       normal(90,9)               7482                    NaN
29       normal(90,9)               1249                    NaN
30      normal(100,1)               1667                    NaN
31      normal(100,1)               1557                    NaN
32       normal(90,9)               2166                    NaN
33       normal(90,9)               3345                    NaN
34      normal(100,1)               4221                    NaN

    Patient_Arrival_Time
0                      0
1                      0
2                      0
3                      0
4                      0
5                      0
6                      0
7                      0
8                      0
9                      0
10                     0
11                     0
12                     0
13                     0
14                     0
15                     0
16                     0
17                     0
18                     0
19                     0
20                     0
21                     0
22                     0
23                     0
24                     0
25                     0
26                     0
27                     0
28                     0
29                     0
30                     0
31                     0
32                     0
33                     0
34                     0
    Row#  Case_Num Case_Type Block_Group Patient_Type Service Procedure  \
0    NaN        23     Addon         GRM    Inpatient   OBGyn    OBGyn3
1    NaN        24     Addon         GRM    Inpatient   OBGyn    OBGyn4
2    NaN        22     Addon         GRM    Inpatient   OBGyn    OBGyn2
3    NaN         8     Block         GRM    Inpatient   OBGyn    OBGyn1
4    1.0         1     Block         XYZ    Inpatient   Ortho    Ortho1
5    2.0         2     Block         XYZ    Inpatient   Ortho    Ortho2
6    3.0         3     Block         ABC   Outpatient    Opth     Opth1
7    4.0         4     Block         ABC   Outpatient    Opth     Opth2
8    5.0         5     Block         RST    Inpatient    Vasc     Vasc1
9    6.0         6     Block         CCR    Inpatient   Ortho    Ortho6
10   7.0         7     Block         CCR    Inpatient   Ortho    Ortho7
11   NaN         9     Addon         XYZ    Inpatient   Ortho    Ortho3
12   NaN        10     Addon         XYZ    Inpatient   Ortho    Ortho4
13   NaN        11     Addon         XYZ    Inpatient   Ortho    Ortho5
14   NaN        12     Addon         XYZ    Inpatient   Ortho    Ortho9
15   NaN        13     Addon         ABC   Outpatient    Opth     Opth2
16   NaN        14     Addon         RST    Inpatient    Vasc     Vasc2
17   NaN        15     Addon         RST    Inpatient    Vasc     Vasc3
18   NaN        16     Addon         RMT    Inpatient     Gen      Gen1
19   NaN        17     Addon         MTC    Inpatient     Gen      Gen2
20   NaN        18     Addon         MTC    Inpatient     Gen      Gen3
21   NaN        19     Addon         MTC    Inpatient     Gen      Gen4
22   NaN        20     Addon         CCR    Inpatient   Ortho    Ortho8
23   NaN        21     Addon         CCR    Inpatient   Ortho    Ortho8
24   NaN        25     Addon         RRR    Inpatient     Gen      Gen5
25   NaN        26     Addon         SSS    Inpatient     Gen      Gen6
26   NaN        27     Addon         SSS    Inpatient     Gen      Gen7
27   NaN        28     Addon         TTT    Inpatient    Vasc     Vasc3
28   NaN        29     Addon         TTT    Inpatient    Vasc     Vasc3
29   NaN        30     Addon         UUU   Outpatient   Optho    Optho4
30   NaN        31     Addon         UUU   Outpatient   Optho    Optho4
31   NaN        32     Addon         UUU   Outpatient   Optho    Optho4
32   NaN        33     Addon         UUU   Outpatient   Optho    Optho4
33   NaN        34     Addon         VVV    Inpatient   Ortho    Ortho9
34   NaN        35     Addon         VVV    Inpatient   Ortho    Ortho2

           Surgeon OR_Suite  Allotted_PreOp_Time Wheels_In_to_Incision_Time  \
0         Dr Grace      NaN                   20               normal(19,2)
1         Dr Grace      NaN                   20               normal(23,3)
2         Dr Grace      OR1                   20               normal(25,3)
3         Dr Grace      OR1                   20               normal(28,3)
4         Dr Smith      OR2                   20               normal(11,2)
5         Dr Smith      OR3                   20                normal(5,1)
6         Dr Brown      OR1                   20                normal(8,1)
7         Dr Brown      OR2                   20               normal(10,1)
8         Dr Jones      OR2                   20                normal(8,1)
9          Dr Mack      OR2                   20               normal(20,2)
10         Dr Mack      OR2                   20               normal(23,3)
11        Dr Smith      OR2                   20                normal(9,1)
12        Dr Smith      OR2                   20               normal(10,1)
13        Dr Smith      OR3                   20               normal(15,6)
14        Dr Smith      OR3                   20               normal(13,1)
15        Dr Brown      OR1                   20               normal(10,1)
16        Dr Jones      OR3                   20               normal(10,1)
17        Dr Jones      OR3                   20               normal(15,2)
18     Dr Brittany      NaN                   20               normal(12,2)
19     Dr Brittany      NaN                   20               normal(23,3)
20     Dr Brittany      NaN                   20               normal(15,2)
21     Dr Brittany      NaN                   20               normal(15,2)
22         Dr Mack      OR3                   20                normal(5,1)
23         Dr Mack      OR2                   20                normal(5,1)
24    Gen Surgeons      OR1                   20                normal(8,1)
25    Gen Surgeons      OR1                   20                normal(5,1)
26    Gen Surgeons      OR1                   20                normal(5,1)
27   Vasc Surgeons      OR3                   20               normal(15,2)
28   Vasc Surgeons      OR1                   20               normal(15,2)
29  Optho Surgeons      NaN                   20                normal(8,1)
30  Optho Surgeons      OR1                   20                normal(8,1)
31  Optho Surgeons      NaN                   20                normal(8,1)
32  Optho Surgeons      NaN                   20                normal(8,1)
33  Ortho Surgeons      NaN                   20               normal(23,3)
34        Dr Smith      OR2                   20                normal(5,1)

   Incision_to_Closure_Time Closure_to_Wheels_Out_Time  \
0              normal(38,4)               normal(19,2)
1              normal(45,5)               normal(23,3)
2              normal(50,5)               normal(25,3)
3              normal(55,6)               normal(28,3)
4              normal(23,3)               normal(11,2)
5              normal(12,2)                normal(6,1)
6              normal(15,2)                normal(8,1)
7               normal(7,2)                normal(5,1)
8              normal(15,2)                normal(4,1)
9              normal(50,5)               normal(20,2)
10             normal(45,5)               normal(23,3)
11             normal(18,2)                normal(9,1)
12             normal(20,2)               normal(10,1)
13            normal(70,15)               normal(15,5)
14             normal(18,2)               normal(12,3)
15              normal(7,2)                normal(5,1)
16             normal(20,2)               normal(10,1)
17             normal(30,3)               normal(15,2)
18             normal(31,4)               normal(12,2)
19             normal(45,5)               normal(23,3)
20             normal(30,3)               normal(15,2)
21             normal(30,3)               normal(15,2)
22             normal(10,1)                normal(5,1)
23             normal(10,1)                normal(5,1)